project_id = "uabdmohhzsertxfishoh"

[functions.subscription-webhook]
verify_jwt = false

[functions.generate-batch-questions]
verify_jwt = true

[functions.send-social-notification]
verify_jwt = false