default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(
      project: "Satoshi_Finance_Game.xcodeproj",
      scheme: "Satoshi_Finance_Game"
    )
    upload_to_testflight
  end
end
