default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(scheme: "Satoshi_Finance_Game") # Troque pelo nome do seu scheme no Xcode
    upload_to_testflight
  end
end
