default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(
      scheme: "Satoshi_Finance_Game",
      export_method: "app-store",
      export_options: {
        signingStyle: "automatic",
        method: "app-store"
      },
      destination: "generic/platform=iOS"
    )
    
    upload_to_testflight
  end
end
