-- Continuar inserindo questões de nível médio e difícil (100 questões)
INSERT INTO public.quiz_questions (question, options, correct_answer, explanation, difficulty, category, tags) VALUES

-- MEDIUM LEVEL QUESTIONS (50)
('Qual é o conceito de custo de oportunidade?', 
'["Custo de uma oportunidade perdida", "Valor que você deixa de ganhar ao escolher uma opção", "Custo fixo de investimentos", "Taxa cobrada por oportunidades"]', 
'Valor que você deixa de ganhar ao escolher uma opção', 
'Custo de oportunidade é o valor da melhor alternativa que você renuncia ao fazer uma escolha financeira.', 
'medium', 'Economia Comportamental', '{"custo oportunidade", "decisões", "economia"}'),

('O que é o efeito juros compostos e por que é poderoso?', 
'["Juros simples aplicados mensalmente", "Juros que rendem juros, crescendo exponencialmente", "Juros pagos pelo banco", "Juros de empréstimos"]', 
'Juros que rendem juros, crescendo exponencialmente', 
'Juros compostos fazem seu dinheiro crescer exponencialmente porque você ganha juros sobre o capital inicial e sobre os juros acumulados.', 
'medium', 'Matemática Financeira', '{"juros compostos", "crescimento", "tempo"}'),

('Como calcular o valor real do seu salário considerando a inflação?', 
'["Salário nominal dividido pela inflação", "Salário nominal menos a taxa de inflação do período", "Salário bruto menos impostos", "Salário líquido mais benefícios"]', 
'Salário nominal menos a taxa de inflação do período', 
'Salário real = (salário nominal / índice de inflação) - para saber o real poder de compra do seu dinheiro.', 
'medium', 'Economia Pessoal', '{"salário real", "inflação", "poder de compra"}'),

('Qual a estratégia mais eficiente para quitar múltiplas dívidas?', 
'["Pagar todas igualmente", "Método avalanche: maiores juros primeiro", "Método bola de neve: menores valores primeiro", "Depende do perfil e situação psicológica"]', 
'Depende do perfil e situação psicológica', 
'Método avalanche economiza mais dinheiro (maiores juros primeiro), mas bola de neve pode ser melhor psicologicamente (menores valores primeiro).', 
'medium', 'Gestão de Dívidas', '{"estratégia", "avalanche", "bola de neve"}'),

('O que é diversificação eficiente em investimentos?', 
'["Comprar muitos ativos diferentes", "Combinar ativos com baixa correlação entre si", "Investir apenas em renda fixa", "Comprar ações de setores diferentes"]', 
'Combinar ativos com baixa correlação entre si', 
'Diversificação eficiente combina ativos que não se movem na mesma direção, reduzindo risco sem sacrificar muito retorno.', 
'medium', 'Teoria de Investimentos', '{"diversificação", "correlação", "risco"}'),

('Como funciona o rebalanceamento de carteira?', 
'["Vender tudo e comprar novamente", "Ajustar proporções dos ativos conforme estratégia original", "Sempre comprar mais do que está subindo", "Trocar investimentos ruins por bons"]', 
'Ajustar proporções dos ativos conforme estratégia original', 
'Rebalanceamento mantém a alocação desejada vendendo ativos que subiram muito e comprando os que caíram, forçando comprar barato e vender caro.', 
'medium', 'Gestão de Carteira', '{"rebalanceamento", "alocação", "disciplina"}'),

('Qual a diferença entre valor nominal e valor presente?', 
'["Não há diferença", "Valor nominal ignora inflação, valor presente considera", "Valor nominal é sempre maior", "Valor presente é o valor futuro"]', 
'Valor nominal ignora inflação, valor presente considera', 
'Valor presente desconta a inflação e custo de oportunidade, mostrando o valor real do dinheiro no tempo atual.', 
'medium', 'Matemática Financeira', '{"valor presente", "valor nominal", "desconto"}'),

('O que é Duration em títulos de renda fixa?', 
'["Prazo até o vencimento", "Sensibilidade do preço à variação de juros", "Tempo para receber cupons", "Duração do investimento"]', 
'Sensibilidade do preço à variação de juros', 
'Duration mede quanto o preço do título varia para cada 1% de mudança na taxa de juros do mercado.', 
'medium', 'Renda Fixa Avançada', '{"duration", "sensibilidade", "juros"}'),

('Como identificar um esquema Ponzi ou pirâmide financeira?', 
'["Prometem retornos baixos", "Prometem retornos altos garantidos sem risco", "Investem em empresas conhecidas", "Têm regulamentação do governo"]', 
'Prometem retornos altos garantidos sem risco', 
'Esquemas fraudulentos prometem retornos irrealisticamente altos "sem risco" e pagam investidores antigos com dinheiro de novos investidores.', 
'medium', 'Educação Financeira', '{"fraude", "pirâmide", "ponzi"}'),

('Qual o impacto da taxa de câmbio nos seus investimentos?', 
'["Não afeta investimentos nacionais", "Afeta investimentos internacionais e empresas exportadoras", "Só afeta quem viaja", "Apenas investimentos em dólar"]', 
'Afeta investimentos internacionais e empresas exportadoras', 
'Câmbio impacta investimentos internacionais diretamente e empresas exportadoras/importadoras indiretamente, mesmo em investimentos nacionais.', 
'medium', 'Investimentos Internacionais', '{"câmbio", "internacional", "exportação"}'),

('O que é o Índice Sharpe e para que serve?', 
'["Índice da bolsa brasileira", "Medida de retorno ajustado ao risco", "Taxa de juros internacional", "Índice de inflação"]', 
'Medida de retorno ajustado ao risco', 
'Índice Sharpe mede o retorno adicional recebido por unidade de risco assumido, ajudando a comparar investimentos.', 
'medium', 'Análise de Investimentos', '{"sharpe", "risco", "retorno"}'),

('Como funciona o sistema de amortização SAC vs PRICE?', 
'["SAC: juros fixos, PRICE: parcelas fixas", "SAC: parcelas decrescentes, PRICE: parcelas fixas", "Não há diferença prática", "SAC é sempre melhor"]', 
'SAC: parcelas decrescentes, PRICE: parcelas fixas', 
'SAC amortiza valor fixo do principal (parcelas decrescentes), PRICE mantém parcelas fixas (mais juros no início).', 
'medium', 'Financiamentos', '{"SAC", "PRICE", "amortização"}'),

('O que são derivativos e quando usar?', 
'["Investimentos derivados de ações", "Instrumentos para hedge ou especulação", "Apenas para especulação", "Investimentos proibidos"]', 
'Instrumentos para hedge ou especulação', 
'Derivativos são contratos baseados em ativos subjacentes, usados para proteção (hedge) ou especulação com alavancagem.', 
'medium', 'Instrumentos Financeiros', '{"derivativos", "hedge", "alavancagem"}'),

('Como calcular o payback de um investimento?', 
'["Retorno dividido pelo investimento", "Tempo necessário para recuperar o investimento", "Lucro menos investimento inicial", "Não é possível calcular"]', 
'Tempo necessário para recuperar o investimento', 
'Payback é o período necessário para que os fluxos de caixa positivos igualem o investimento inicial.', 
'medium', 'Análise de Investimentos', '{"payback", "recuperação", "fluxo de caixa"}'),

('Qual a diferença entre inflação oficial e inflação pessoal?', 
'["Não há diferença", "Oficial é média geral, pessoal reflete sua cesta de consumo", "Pessoal é sempre maior", "Oficial é sempre maior"]', 
'Oficial é média geral, pessoal reflete sua cesta de consumo', 
'Inflação oficial (IPCA) é média nacional, mas sua inflação pessoal pode ser diferente dependendo de seus hábitos de consumo.', 
'medium', 'Economia Pessoal', '{"inflação", "pessoal", "cesta de consumo"}'),

('O que é arbitragem nos investimentos?', 
'["Negociação entre amigos", "Aproveitar diferenças de preços para lucro sem risco", "Tipo de derivativo", "Modalidade de empréstimo"]', 
'Aproveitar diferenças de preços para lucro sem risco', 
'Arbitragem explora diferenças temporárias de preços do mesmo ativo em mercados diferentes para lucro sem risco.', 
'medium', 'Estratégias Avançadas', '{"arbitragem", "diferenças", "sem risco"}'),

('Como funciona o sistema de tributação progressiva?', 
'["Taxa fixa para todos", "Alíquotas maiores para rendas maiores", "Taxa zero para todos", "Taxa baseada em idade"]', 
'Alíquotas maiores para rendas maiores', 
'Tributação progressiva aplica alíquotas crescentes conforme a renda aumenta, fazendo quem ganha mais pagar proporcionalmente mais.', 
'medium', 'Tributação', '{"progressiva", "alíquotas", "justiça social"}'),

('O que é beta de um ativo e como interpretar?', 
'["Versão beta de software", "Sensibilidade do ativo em relação ao mercado", "Taxa de administração", "Tipo de fundo"]', 
'Sensibilidade do ativo em relação ao mercado', 
'Beta mede quanto um ativo varia em relação ao mercado: beta 1 = igual ao mercado, >1 = mais volátil, <1 = menos volátil.', 
'medium', 'Análise de Risco', '{"beta", "volatilidade", "mercado"}'),

('Como calcular o ROI (Return on Investment)?', 
'["Lucro dividido pelo investimento x 100", "Investimento dividido pelo lucro", "Receita menos custos", "Não é possível calcular"]', 
'Lucro dividido pelo investimento x 100', 
'ROI = (Ganho - Investimento) / Investimento x 100. Mede a eficiência de um investimento em termos percentuais.', 
'medium', 'Métricas Financeiras', '{"ROI", "retorno", "eficiência"}'),

('O que é funding e como funciona?', 
'["Tipo de fundo de investimento", "Captação de recursos para financiar atividades", "Taxa cobrada pelos bancos", "Sistema de pagamentos"]', 
'Captação de recursos para financiar atividades', 
'Funding é o processo de obter recursos financeiros para financiar operações, investimentos ou crescimento de empresas.', 
'medium', 'Mercado de Capitais', '{"funding", "captação", "financiamento"}'),

('Como identificar bolhas especulativas no mercado?', 
'["Preços sempre sobem", "Crescimento exponencial descolado dos fundamentos", "Mercado muito regulamentado", "Baixa volatilidade"]', 
'Crescimento exponencial descolado dos fundamentos', 
'Bolhas caracterizam-se por preços que sobem muito acima do valor real, impulsionados por especulação e euforia irracional.', 
'medium', 'Psicologia de Mercado', '{"bolha", "especulação", "fundamentos"}'),

('Qual a diferença entre rentabilidade nominal e real?', 
'["Não há diferença", "Nominal ignora inflação, real desconta inflação", "Real é sempre maior", "Nominal é mais importante"]', 
'Nominal ignora inflação, real desconta inflação', 
'Rentabilidade nominal é o percentual bruto, real é descontada a inflação, mostrando o ganho efetivo de poder de compra.', 
'medium', 'Análise de Retorno', '{"nominal", "real", "inflação"}'),

('O que é risco sistêmico vs risco não-sistêmico?', 
'["Não há diferença", "Sistêmico afeta todo o mercado, não-sistêmico é específico", "Sistêmico é menor", "Não-sistêmico é pior"]', 
'Sistêmico afeta todo o mercado, não-sistêmico é específico', 
'Risco sistêmico (mercado) não pode ser diversificado, risco não-sistêmico (específico) pode ser reduzido com diversificação.', 
'medium', 'Gestão de Risco', '{"sistêmico", "não-sistêmico", "diversificação"}'),

('Como funciona o sistema de rating de crédito?', 
'["Avaliação aleatória", "Análise da capacidade de pagamento", "Baseado apenas na renda", "Sistema governamental apenas"]', 
'Análise da capacidade de pagamento', 
'Rating avalia a probabilidade de inadimplência considerando histórico, renda, patrimônio e outros fatores de risco.', 
'medium', 'Mercado de Crédito', '{"rating", "crédito", "risco"}'),

('O que é carry trade e quais os riscos?', 
'["Transporte de dinheiro", "Tomar emprestado em moeda de juros baixos para investir em juros altos", "Tipo de cartão", "Sistema de pagamento"]', 
'Tomar emprestado em moeda de juros baixos para investir em juros altos', 
'Carry trade aproveita diferenças de juros entre países, mas envolve risco cambial significativo.', 
'medium', 'Estratégias Internacionais', '{"carry trade", "juros", "câmbio"}'),

('Como calcular o custo efetivo total (CET) de um empréstimo?', 
'["Apenas a taxa de juros", "Todos os custos incluídos expressos em taxa anual", "Valor total a pagar", "Taxa administrativa"]', 
'Todos os custos incluídos expressos em taxa anual', 
'CET inclui juros, tarifas, seguros e todos os custos do empréstimo expressos em uma única taxa anual para comparação.', 
'medium', 'Custos de Crédito', '{"CET", "custos", "transparência"}'),

('O que é hedge accounting?', 
'["Contabilidade de fundos hedge", "Técnica contábil para operações de proteção", "Sistema de cobrança", "Tipo de auditoria"]', 
'Técnica contábil para operações de proteção', 
'Hedge accounting permite tratar contabilmente operações de proteção de forma que reflitam economicamente a estratégia de hedge.', 
'medium', 'Contabilidade Financeira', '{"hedge", "contabilidade", "proteção"}'),

('Como funciona o mercado de balcão organizado?', 
'["Mercado físico presencial", "Mercado eletrônico regulamentado fora de bolsa", "Mercado informal", "Apenas para grandes investidores"]', 
'Mercado eletrônico regulamentado fora de bolsa', 
'Balcão organizado oferece negociação eletrônica regulamentada de títulos que não estão listados em bolsa.', 
'medium', 'Estrutura de Mercado', '{"balcão", "organizado", "regulamentação"}'),

('O que são covenants em contratos de dívida?', 
'["Cláusulas de proteção para credores", "Taxas de juros variáveis", "Garantias físicas", "Seguros obrigatórios"]', 
'Cláusulas de proteção para credores', 
'Covenants são cláusulas que impõem obrigações ou restrições ao devedor para proteger os interesses do credor.', 
'medium', 'Estruturas de Crédito', '{"covenants", "proteção", "credores"}'),

('Como calcular o valor econômico agregado (EVA)?', 
'["Receita menos custos", "Lucro operacional menos custo de capital", "Valor de mercado da empresa", "Patrimônio líquido"]', 
'Lucro operacional menos custo de capital', 
'EVA = NOPAT - (Capital Investido x WACC). Mede se a empresa gera valor acima do custo do capital empregado.', 
'medium', 'Valuation', '{"EVA", "valor", "capital"}'),

('O que é stress testing em investimentos?', 
'["Teste de estresse físico", "Simulação de cenários adversos extremos", "Análise de volatilidade normal", "Teste de liquidez"]', 
'Simulação de cenários adversos extremos', 
'Stress testing simula situações extremas de mercado para avaliar como a carteira se comportaria em crises severas.', 
'medium', 'Gestão de Risco', '{"stress test", "cenários", "extremos"}'),

('Como funciona o sistema de marcação a mercado?', 
'["Preço de compra sempre", "Avaliação pelos preços atuais de mercado", "Custo histórico", "Valor contábil"]', 
'Avaliação pelos preços atuais de mercado', 
'Marcação a mercado atualiza o valor dos ativos pelos preços atuais, refletindo perdas e ganhos não realizados.', 
'medium', 'Valuation de Ativos', '{"marcação", "mercado", "preços atuais"}'),

('O que é volatilidade implícita vs histórica?', 
'["Não há diferença", "Implícita vem de opções, histórica de preços passados", "Histórica é sempre maior", "Implícita é mais confiável"]', 
'Implícita vem de opções, histórica de preços passados', 
'Volatilidade histórica calcula-se dos preços passados, implícita é derivada dos preços das opções (expectativa futura).', 
'medium', 'Análise de Volatilidade', '{"volatilidade", "implícita", "histórica"}'),

('Como identificar conflitos de interesse em assessoria financeira?', 
'["Sempre existem", "Quando o assessor ganha mais vendendo produtos específicos", "Nunca existem", "Apenas em bancos"]', 
'Quando o assessor ganha mais vendendo produtos específicos', 
'Conflito existe quando a remuneração do assessor não está alinhada com seus melhores interesses (comissões vs honorários).', 
'medium', 'Assessoria Financeira', '{"conflito", "interesse", "comissões"}'),

('O que é duration matching em ALM?', 
'["Combinar prazos iguais", "Igualar duration de ativos e passivos", "Estratégia de trading", "Tipo de hedge"]', 
'Igualar duration de ativos e passivos', 
'Duration matching protege patrimônio contra mudanças de juros igualando a sensibilidade dos ativos e passivos.', 
'medium', 'Asset Liability Management', '{"duration", "matching", "proteção"}'),

('Como funciona o sistema de tributação come-cotas?', 
'["Taxa fixa anual", "Antecipação semestral do IR sobre rendimentos", "Isento de impostos", "Tributação na fonte"]', 
'Antecipação semestral do IR sobre rendimentos', 
'Come-cotas antecipa IR semestralmente sobre fundos de longo prazo, sendo compensado na declaração anual.', 
'medium', 'Tributação de Investimentos', '{"come-cotas", "antecipação", "IR"}'),

('O que é liquidity trap em economia?', 
'["Armadilha de liquidez", "Situação onde política monetária perde eficácia", "Falta de dinheiro no mercado", "Excesso de crédito"]', 
'Situação onde política monetária perde eficácia', 
'Liquidity trap ocorre quando juros próximos de zero fazem política monetária perder efetividade para estimular economia.', 
'medium', 'Macroeconomia', '{"liquidity trap", "política monetária", "juros"}'),

('Como calcular o alpha de Jensen?', 
'["Retorno menos risco", "Retorno real menos retorno esperado pelo CAPM", "Beta vezes mercado", "Volatilidade do ativo"]', 
'Retorno real menos retorno esperado pelo CAPM', 
'Alpha de Jensen = Retorno da carteira - [Taxa livre risco + Beta x (Retorno mercado - Taxa livre risco)].', 
'medium', 'Performance de Carteira', '{"alpha", "Jensen", "CAPM"}'),

('O que é window dressing em fundos?', 
'["Decoração de escritórios", "Maquiar carteira antes de divulgações", "Estratégia de marketing", "Tipo de auditoria"]', 
'Maquiar carteira antes de divulgações', 
'Window dressing é ajustar temporariamente a carteira antes de relatórios para melhorar aparência e atrair investidores.', 
'medium', 'Ética em Investimentos', '{"window dressing", "maquiagem", "carteira"}'),

('Como funciona o mecanismo de transmissão da política monetária?', 
'["Direto para preços", "Através de canais como crédito, câmbio e expectativas", "Apenas via bancos", "Sem mecanismo definido"]', 
'Através de canais como crédito, câmbio e expectativas', 
'Política monetária afeta economia via canais: taxa de juros, crédito, câmbio, preços de ativos e expectativas.', 
'medium', 'Política Monetária', '{"transmissão", "canais", "economia"}'),

('O que é moral hazard em seguros e finanças?', 
'["Risco moral das pessoas", "Mudança de comportamento após proteção", "Problema ético apenas", "Tipo de seguro"]', 
'Mudança de comportamento após proteção', 
'Moral hazard ocorre quando proteção (seguro, garantias) leva a comportamentos mais arriscados por parte do protegido.', 
'medium', 'Teoria dos Contratos', '{"moral hazard", "comportamento", "risco"}'),

('Como identificar empresas com vantagem competitiva sustentável?', 
'["Maior lucro atual", "Retorno sobre capital consistentemente alto", "Maior tamanho", "Mais funcionários"]', 
'Retorno sobre capital consistentemente alto', 
'Vantagem competitiva sustentável manifesta-se em retornos sobre capital consistentemente superiores ao custo de capital.', 
'medium', 'Análise Fundamentalista', '{"vantagem competitiva", "ROIC", "sustentável"}'),

('O que é credit spread e o que indica?', 
'["Diferença entre taxas de crédito e livre de risco", "Tipo de derivativo", "Taxa de administração", "Imposto sobre crédito"]', 
'Diferença entre taxas de crédito e livre de risco', 
'Credit spread reflete o prêmio de risco exigido para compensar probabilidade de inadimplência vs títulos sem risco.', 
'medium', 'Análise de Crédito', '{"credit spread", "risco", "prêmio"}'),

('Como funciona o sistema de rating ESG?', 
'["Avaliação apenas financeira", "Critérios ambientais, sociais e de governança", "Sistema governamental", "Rating de crédito"]', 
'Critérios ambientais, sociais e de governança', 
'Rating ESG avalia empresas em aspectos Environmental, Social e Governance, influenciando decisões de investimento sustentável.', 
'medium', 'Investimento Sustentável', '{"ESG", "sustentabilidade", "governança"}'),

('O que é yield curve inversion e seu significado?', 
'["Curva sempre crescente", "Juros curto prazo maiores que longo prazo", "Gráfico invertido", "Erro de cálculo"]', 
'Juros curto prazo maiores que longo prazo', 
'Inversão da curva de juros (curto > longo) historicamente precede recessões, indicando expectativas pessimistas.', 
'medium', 'Análise Macroeconômica', '{"yield curve", "inversão", "recessão"}'),

('Como calcular o free cash flow de uma empresa?', 
'["Receita menos custos", "Fluxo operacional menos investimentos em capital", "Lucro líquido", "Caixa no balanço"]', 
'Fluxo operacional menos investimentos em capital', 
'Free cash flow = Fluxo de caixa operacional - CAPEX. Representa dinheiro disponível para acionistas e credores.', 
'medium', 'Análise Financeira', '{"free cash flow", "operacional", "CAPEX"}'),

-- HARD LEVEL QUESTIONS (50)
('Qual o impacto da convexidade nos preços de bonds durante mudanças bruscas de juros?', 
'["Não há impacto", "Melhora a aproximação da duration para grandes variações", "Piora a precisão", "Só afeta títulos longos"]', 
'Melhora a aproximação da duration para grandes variações', 
'Convexidade captura a curvatura da relação preço-yield, melhorando a estimativa de mudanças de preço para grandes variações de juros.', 
'hard', 'Renda Fixa Avançada', '{"convexidade", "bonds", "duration"}'),

('Como implementar uma estratégia de pairs trading eficiente?', 
'["Comprar duas ações quaisquer", "Identificar ativos cointegrados e explorar divergências temporárias", "Sempre long e short simultaneamente", "Apenas com ações do mesmo setor"]', 
'Identificar ativos cointegrados e explorar divergências temporárias', 
'Pairs trading requer análise de cointegração para identificar pares que convergem historicamente, apostando na reversão de divergências.', 
'hard', 'Estratégias Quantitativas', '{"pairs trading", "cointegração", "divergências"}'),

('Qual o modelo mais adequado para precificar opções americanas?', 
'["Black-Scholes sempre", "Modelos binomiais ou trinomiais", "Monte Carlo simples", "Não é possível precificar"]', 
'Modelos binomiais ou trinomiais', 
'Opções americanas podem ser exercidas antecipadamente, requerendo modelos de árvore que capturam essa flexibilidade.', 
'hard', 'Derivativos Avançados', '{"opções americanas", "binomial", "exercício antecipado"}'),

('Como calcular o VaR (Value at Risk) usando simulação de Monte Carlo?', 
'["Impossível calcular", "Simular milhares de cenários e encontrar percentil desejado", "Usar apenas volatilidade histórica", "Fórmula simples de média"]', 
'Simular milhares de cenários e encontrar percentil desejado', 
'Monte Carlo VaR simula milhares de cenários futuros e identifica o percentil correspondente ao nível de confiança desejado.', 
'hard', 'Gestão de Risco Quantitativa', '{"VaR", "Monte Carlo", "simulação"}'),

('Qual o papel do lambda na estratégia de Black-Litterman?', 
'["Não existe lambda", "Parâmetro que controla confiança nas views vs equilíbrio", "Taxa de desconto", "Medida de risco"]', 
'Parâmetro que controla confiança nas views vs equilíbrio', 
'Lambda em Black-Litterman pondera entre alocação de equilíbrio de mercado e views específicas do investidor.', 
'hard', 'Otimização de Carteira', '{"Black-Litterman", "lambda", "views"}'),

('Como implementar uma estratégia de volatility arbitrage?', 
'["Comprar alta volatilidade", "Explorar diferenças entre volatilidade implícita e realizada", "Vender sempre opções", "Comprar sempre opções"]', 
'Explorar diferenças entre volatilidade implícita e realizada', 
'Volatility arbitrage explora discrepâncias entre volatilidade implícita das opções e expectativa de volatilidade futura realizada.', 
'hard', 'Trading Quantitativo', '{"volatility arbitrage", "implícita", "realizada"}'),

('Qual o método mais eficiente para hedge de carteira com alta correlação?', 
'["Diversificação simples", "Principal Component Analysis para hedge", "Hedge individual de cada ativo", "Não é possível fazer hedge"]', 
'Principal Component Analysis para hedge', 
'PCA identifica fatores comuns de risco, permitindo hedge mais eficiente de carteiras com alta correlação usando menos instrumentos.', 
'hard', 'Hedge Avançado', '{"PCA", "hedge", "fatores comuns"}'),

('Como calcular o CVA (Credit Valuation Adjustment) de derivativos OTC?', 
'["Usar apenas spread de crédito", "Simular exposição futura e aplicar probabilidade de default", "Multiplicar nocional por spread", "Não é calculável"]', 
'Simular exposição futura e aplicar probabilidade de default', 
'CVA requer simulação da exposição futura esperada do derivativo e aplicação da curva de probabilidade de default da contraparte.', 
'hard', 'Risco de Contraparte', '{"CVA", "exposição futura", "default"}'),

('Qual a principal limitação do modelo CAPM e como superá-la?', 
'["Beta instável", "Assume mercado eficiente; usar modelos multifatoriais", "Não considera dividendos", "Muito complexo"]', 
'Assume mercado eficiente; usar modelos multifatoriais', 
'CAPM assume mercado eficiente e um só fator de risco. Modelos como Fama-French capturam fatores adicionais de risco e retorno.', 
'hard', 'Teoria de Apreçamento', '{"CAPM", "limitações", "multifatorial"}'),

('Como implementar uma estratégia de statistical arbitrage baseada em mean reversion?', 
'["Comprar qualquer ativo que caiu", "Identificar séries estacionárias e explorar desvios da média", "Sempre fazer short", "Usar apenas análise técnica"]', 
'Identificar séries estacionárias e explorar desvios da média', 
'Statistical arbitrage requer identificação de séries estacionárias (teste ADF) e exploração sistemática de reversões à média.', 
'hard', 'Quantitative Finance', '{"stat arb", "mean reversion", "estacionariedade"}'),

('Qual o impacto do smile de volatilidade na precificação de opções exóticas?', 
'["Não afeta opções exóticas", "Requer modelos de volatilidade local ou estocástica", "Apenas muda o preço linearmente", "Só afeta opções vanilla"]', 
'Requer modelos de volatilidade local ou estocástica', 
'Smile de volatilidade invalida Black-Scholes para exóticas, requerendo modelos como Dupire ou Heston para precificação precisa.', 
'hard', 'Engenharia Financeira', '{"smile", "exóticas", "volatilidade local"}'),

('Como estruturar um CDO sintético de forma eficiente?', 
'["Apenas com bonds corporativos", "Usar CDS para criar exposição sem comprar ativos", "Só com hipotecas", "Não é possível estruturar"]', 
'Usar CDS para criar exposição sem comprar ativos', 
'CDO sintético usa credit default swaps para criar exposição de crédito sem possuir fisicamente os ativos de referência.', 
'hard', 'Produtos Estruturados', '{"CDO sintético", "CDS", "exposição sintética"}'),

('Qual a metodologia correta para backtesting de estratégias de high-frequency trading?', 
'["Dados diários são suficientes", "Usar dados tick-by-tick com consideração de microestrutura", "Apenas dados de fechamento", "Backtesting não é necessário"]', 
'Usar dados tick-by-tick com consideração de microestrutura', 
'HFT requer dados de alta frequência, considerando bid-ask spreads, latência, impact de mercado e custos de transação reais.', 
'hard', 'High Frequency Trading', '{"HFT", "backtesting", "microestrutura"}'),

('Como implementar um modelo de Stochastic Volatility para apreçamento?', 
'["Volatilidade sempre constante", "Modelar volatilidade como processo estocástico próprio", "Usar apenas volatilidade histórica", "Impossível implementar"]', 
'Modelar volatilidade como processo estocástico próprio', 
'Modelos como Heston tratam volatilidade como variável aleatória própria, capturando clustering e mean reversion da volatilidade.', 
'hard', 'Modelos Estocásticos', '{"stochastic volatility", "Heston", "clustering"}'),

('Qual o método mais preciso para medir tail risk em carteiras complexas?', 
'["VaR normal", "Expected Shortfall com distribuições fat-tailed", "Desvio padrão", "Sharpe ratio"]', 
'Expected Shortfall com distribuições fat-tailed', 
'Expected Shortfall (CVaR) mede risco de cauda além do VaR, especialmente importante com distribuições fat-tailed reais.', 
'hard', 'Tail Risk Management', '{"expected shortfall", "tail risk", "fat tails"}'),

('Como calcular o regulatory capital sob Basel III para risco de mercado?', 
'["10% dos ativos", "Standardised Approach ou Internal Models Approach", "5% do patrimônio", "Não há cálculo definido"]', 
'Standardised Approach ou Internal Models Approach', 
'Basel III permite SA (padronizado) ou IMA (modelos internos com VaR/ES) para cálculo de capital para risco de mercado.', 
'hard', 'Regulamentação Bancária', '{"Basel III", "capital regulatório", "IMA"}'),

('Qual a melhor abordagem para hedging de opções gamma?', 
'["Hedge apenas delta", "Rebalanceamento dinâmico com underlying e outras opções", "Hedge estático apenas", "Não fazer hedge de gamma"]', 
'Rebalanceamento dinâmico com underlying e outras opções', 
'Hedge de gamma requer rebalanceamento frequente usando o ativo subjacente e/ou outras opções para manter gamma neutro.', 
'hard', 'Options Trading Avançado', '{"gamma hedge", "rebalanceamento", "dinâmico"}'),

('Como implementar uma estratégia de momentum cross-sectional?', 
'["Comprar ativos que subiram", "Ranking relativo e long-short dos extremos", "Apenas momentum temporal", "Comprar índices"]', 
'Ranking relativo e long-short dos extremos', 
'Momentum cross-sectional rankeia ativos por performance relativa, fazendo long nos melhores e short nos piores.', 
'hard', 'Factor Investing', '{"momentum cross-sectional", "ranking", "long-short"}'),

('Qual o método correto para stress testing de carteiras com derivativos complexos?', 
'["Apenas cenários históricos", "Full revaluation com modelos de pricing completos", "Aproximação linear", "Não é possível"]', 
'Full revaluation com modelos de pricing completos', 
'Derivativos complexos têm payoffs não-lineares, requerendo full revaluation com modelos completos para stress testing preciso.', 
'hard', 'Risk Management Avançado', '{"stress testing", "full revaluation", "não-linear"}'),

('Como calcular o FRTB capital charge para trading book?', 
'["VaR histórico simples", "Sensitivities-based Approach ou Default Risk Charge", "10% dos ativos", "Multiplicar notional por 8%"]', 
'Sensitivities-based Approach ou Default Risk Charge', 
'FRTB (Fundamental Review Trading Book) usa SA baseado em sensitividades ou DRC para risco de default no trading book.', 
'hard', 'Regulamentação FRTB', '{"FRTB", "SA", "trading book"}'),

('Qual a metodologia para calibração de modelos de smile de volatilidade?', 
'["Usar apenas ATM volatility", "Minimizar erro quadrático entre preços modelo vs mercado", "Calibrar apenas com histórico", "Não é necessário calibrar"]', 
'Minimizar erro quadrático entre preços modelo vs mercado', 
'Calibração de smile ajusta parâmetros do modelo para minimizar diferenças entre preços teóricos e observados no mercado.', 
'hard', 'Model Calibration', '{"calibração", "smile", "otimização"}'),

('Como implementar estratégia de capital structure arbitrage?', 
'["Arbitrar entre debt e equity da mesma empresa", "Comprar ações baratas", "Vender bonds caros", "Não existe tal estratégia"]', 
'Arbitrar entre debt e equity da mesma empresa', 
'Capital structure arbitrage explora mispricing entre instrumentos da mesma empresa (bonds vs stocks, diferentes seniorities).', 
'hard', 'Credit Trading', '{"capital structure", "arbitrage", "debt equity"}'),

('Qual o papel do numeraire na mudança de medida em finanças quantitativas?', 
'["Apenas unidade monetária", "Asset usado como deflator para mudança de probabilidade", "Taxa de juros", "Volatilidade de referência"]', 
'Asset usado como deflator para mudança de probabilidade', 
'Numeraire permite mudança de medida de probabilidade, facilitando precificação ao eliminar drift de certos ativos.', 
'hard', 'Matemática Financeira', '{"numeraire", "mudança medida", "deflator"}'),

('Como estruturar um interest rate swap com embedded options?', 
'["Swap vanilla apenas", "Incorporar caps, floors ou swaptions no design", "Apenas fixed vs floating", "Não é possível"]', 
'Incorporar caps, floors ou swaptions no design', 
'Swaps com opções embarcadas combinam swap básico com derivativos de taxa, oferecendo proteção ou oportunidades adicionais.', 
'hard', 'Structured Products', '{"swap", "embedded options", "caps floors"}'),

('Qual método para otimização de carteira sob restrições de turnover?', 
'["Markowitz simples", "Programação quadrática com penalização de turnover", "Igual peso sempre", "Não considerar turnover"]', 
'Programação quadrática com penalização de turnover', 
'Otimização com turnover constraints usa programação quadrática adicionando penalty term para custos de transação.', 
'hard', 'Portfolio Optimization', '{"turnover constraints", "programação quadrática", "custos transação"}'),

('Como implementar modelo de jump diffusion para pricing de opções?', 
'["Apenas diffusion", "Combinar Brownian motion com processo de Poisson", "Só processo de salto", "Modelo determinístico"]', 
'Combinar Brownian motion com processo de Poisson', 
'Jump diffusion (Merton) adiciona saltos aleatórios ao movimento Browniano, capturando descontinuidades nos preços.', 
'hard', 'Modelos de Salto', '{"jump diffusion", "Merton", "Poisson"}'),

('Qual a técnica correta para hedge de correlation risk em basket options?', 
'["Hedge apenas delta", "Usar matriz de correlação e hedge com pares subjacentes", "Não fazer hedge", "Hedge apenas gamma"]', 
'Usar matriz de correlação e hedge com pares subjacentes', 
'Correlation risk em baskets requer hedge considerando mudanças na estrutura de correlação entre os ativos subjacentes.', 
'hard', 'Multi-Asset Derivatives', '{"correlation risk", "basket options", "hedge"}'),

('Como calcular economic capital para operational risk?', 
'["% fixo dos ativos", "Loss Distribution Approach baseado em dados internos/externos", "Multiplicar receita por fator", "Não é calculável"]', 
'Loss Distribution Approach baseado em dados internos/externos', 
'Economic capital para op risk usa LDA combinando dados de frequência e severidade de perdas operacionais.', 
'hard', 'Operational Risk', '{"economic capital", "LDA", "op risk"}'),

('Qual metodologia para backtesting de modelos de VaR com overlapping returns?', 
'["Teste simples de cobertura", "Ajustar para autocorrelação com Newey-West", "Ignorar overlapping", "Não é possível testar"]', 
'Ajustar para autocorrelação com Newey-West', 
'Overlapping returns criam autocorrelação nos testes de VaR, requerendo ajustes estatísticos como Newey-West HAC.', 
'hard', 'VaR Backtesting', '{"overlapping returns", "autocorrelação", "Newey-West"}'),

('Como implementar estratégia de dispersion trading em índices?', 
'["Comprar índice e componentes", "Long volatilidade implícita do índice vs short das componentes", "Short índice", "Long apenas componentes"]', 
'Long volatilidade implícida do índice vs short das componentes', 
'Dispersion trading aposta na diferença entre volatilidade implícita do índice e média ponderada das volatilidades das componentes.', 
'hard', 'Vol Trading Advanced', '{"dispersion trading", "índice vs componentes", "volatilidade"}'),

('Qual o método para precificar swaptions usando modelo Hull-White?', 
'["Black formula apenas", "Árvore trinomial com mean reversion", "Monte Carlo simples", "Não é possível precificar"]', 
'Árvore trinomial com mean reversion', 
'Hull-White permite precificação analítica ou numérica de swaptions incorporando mean reversion das taxas de juros.', 
'hard', 'Interest Rate Derivatives', '{"Hull-White", "swaptions", "mean reversion"}'),

('Como estruturar um CDS index trade para hedge de portfolio credit risk?', 
'["Comprar proteção individual", "Usar índices como CDX/iTraxx proporcionalmente ao risco", "Vender proteção sempre", "Não usar índices"]', 
'Usar índices como CDX/iTraxx proporcionalmente ao risco', 
'CDS indices oferecem hedge eficiente para portfolios diversificados, com liquidez superior aos single names.', 
'hard', 'Credit Portfolio Management', '{"CDS index", "CDX iTraxx", "portfolio hedge"}'),

('Qual técnica para model validation de credit risk models?', 
'["Apenas backtesting", "Cross-validation, champion-challenger, stress testing", "Usar apenas in-sample fit", "Validação não necessária"]', 
'Cross-validation, champion-challenger, stress testing', 
'Model validation robusta combina técnicas estatísticas, comparação de modelos e teste sob stress para garantir robustez.', 
'hard', 'Model Risk Management', '{"model validation", "champion challenger", "robustez"}'),

('Como implementar dynamic hedging para exotic options com path dependency?', 
'["Hedge estático", "Simulação Monte Carlo com rehedging baseado em greeks", "Não fazer hedge", "Hedge apenas no vencimento"]', 
'Simulação Monte Carlo com rehedging baseado em greeks', 
'Exóticas path-dependent requerem hedge dinâmico simulado, recalculando greeks ao longo dos paths possíveis.', 
'hard', 'Exotic Options Hedging', '{"dynamic hedging", "path dependent", "Monte Carlo"}'),

('Qual metodologia para asset allocation sob regime switching?', 
'["Alocação fixa", "Markov switching models com probabilidades de transição", "Média móvel simples", "Buy and hold"]', 
'Markov switching models com probabilidades de transição', 
'Regime switching usa modelos de Markov para identificar regimes diferentes e ajustar alocação baseado em probabilidades de transição.', 
'hard', 'Dynamic Asset Allocation', '{"regime switching", "Markov", "probabilidades transição"}'),

('Como calcular XVA (X-Value Adjustments) para derivativos OTC?', 
'["Apenas CVA", "CVA + DVA + FVA + KVA + outros ajustes", "Spread simples", "Não calcular ajustes"]', 
'CVA + DVA + FVA + KVA + outros ajustes', 
'XVA representa conjunto completo de ajustes: Credit (CVA), Debt (DVA), Funding (FVA), Capital (KVA) e outros.', 
'hard', 'XVA Framework', '{"XVA", "CVA DVA FVA", "ajustes derivativos"}'),

('Qual estratégia para liquidity risk management em market making?', 
'["Ignorar liquidez", "Dynamic bid-ask adjustment baseado em inventory e flow", "Spread fixo sempre", "Não fazer market making"]', 
'Dynamic bid-ask adjustment baseado em inventory e flow', 
'Market making requer ajuste dinâmico de spreads baseado em posição atual, fluxo de ordens e condições de liquidez.', 
'hard', 'Market Making', '{"liquidity risk", "dynamic pricing", "inventory"}'),

('Como implementar multi-factor model para fixed income attribution?', 
'["Single factor apenas", "Decomposição por duration, credit, currency, sector", "Apenas carry", "Attribution não necessária"]', 
'Decomposição por duration, credit, currency, sector', 
'Attribution em renda fixa requer decomposição multi-fatorial considerando diferentes fontes de risco e retorno.', 
'hard', 'Fixed Income Attribution', '{"multi-factor", "attribution", "duration credit"}'),

('Qual método para otimização de execution em algorithmic trading?', 
'["Market orders sempre", "Minimizar implementation shortfall via optimal scheduling", "Limit orders apenas", "Execução aleatória"]', 
'Minimizar implementation shortfall via optimal scheduling', 
'Execution optimization balança market impact vs timing risk usando modelos de Almgren-Chriss para scheduling ótimo.', 
'hard', 'Algorithmic Trading', '{"execution optimization", "implementation shortfall", "scheduling"}'),

('Como estruturar variance swap para hedge de volatility exposure?', 
'["Swap de preços", "Contrato sobre volatilidade realizada vs strike fixo", "Opção sobre volatilidade", "Futuro de volatilidade"]', 
'Contrato sobre volatilidade realizada vs strike fixo', 
'Variance swap paga diferença entre volatilidade realizada e strike, oferecendo exposição pura à volatilidade.', 
'hard', 'Volatility Products', '{"variance swap", "volatilidade realizada", "pure vol exposure"}'),

('Qual técnica para stress testing de liquidity risk em trading portfolios?', 
'["Apenas cenários históricos", "Simulação de widening de spreads e redução de volumes", "VaR normal", "Não fazer stress test"]', 
'Simulação de widening de spreads e redução de volumes', 
'Liquidity stress testing simula deterioração das condições de mercado: spreads maiores, volumes menores, gaps de preços.', 
'hard', 'Liquidity Risk Management', '{"liquidity stress", "spreads widening", "volume reduction"}');

-- Índices para melhor performance
CREATE INDEX idx_quiz_questions_difficulty ON public.quiz_questions(difficulty);
CREATE INDEX idx_quiz_questions_category ON public.quiz_questions(category);
CREATE INDEX idx_user_question_progress_user_id ON public.user_question_progress(user_id);
CREATE INDEX idx_user_question_progress_next_review ON public.user_question_progress(next_review_date);
CREATE INDEX idx_quiz_sessions_user_id ON public.quiz_sessions(user_id);