-- Inserir perguntas para categoria technology (Neural Network Championship)
INSERT INTO public.quiz_questions (question, options, correct_answer, explanation, difficulty, category, tags) VALUES
('O que é Machine Learning?', '["Programação manual de regras", "Algoritmos que aprendem com dados", "Linguagem de programação", "Sistema operacional"]', 'Algoritmos que aprendem com dados', 'Machine Learning permite que sistemas aprendam automaticamente a partir de dados sem serem explicitamente programados.', 'medium', 'technology', '["ia", "machine learning"]'),
('Qual a diferença entre AI e ML?', '["São a mesma coisa", "AI é mais amplo que ML", "ML é mais amplo que AI", "Não há relação"]', 'AI é mais amplo que ML', 'Inteligência Artificial é o campo geral, enquanto Machine Learning é uma subcategoria da AI.', 'easy', 'technology', '["ia", "conceitos"]'),
('O que são Redes Neurais?', '["Cabos de internet", "Modelos inspirados no cérebro", "Protocolos de comunicação", "Bancos de dados"]', 'Modelos inspirados no cérebro', 'Redes neurais são modelos computacionais inspirados na estrutura e funcionamento dos neurônios biológicos.', 'medium', 'technology', '["redes neurais", "ia"]'),
('O que é Deep Learning?', '["Aprender mergulho", "ML com redes neurais profundas", "Programação baixo nível", "Análise superficial"]', 'ML com redes neurais profundas', 'Deep Learning usa redes neurais com múltiplas camadas para aprender representações complexas dos dados.', 'hard', 'technology', '["deep learning", "redes neurais"]'),
('Para que serve o Big Data?', '["Armazenar fotos", "Analisar grandes volumes de dados", "Jogar games", "Editar vídeos"]', 'Analisar grandes volumes de dados', 'Big Data refere-se a conjuntos de dados muito grandes que requerem ferramentas especiais para análise.', 'easy', 'technology', '["big data", "dados"]'),
('O que é Blockchain?', '["Moeda digital", "Livro-razão distribuído", "Aplicativo móvel", "Sistema bancário"]', 'Livro-razão distribuído', 'Blockchain é uma tecnologia de livro-razão distribuído que mantém registros seguros e imutáveis.', 'medium', 'technology', '["blockchain", "tecnologia"]'),
('O que é IoT?', '["Internet das Coisas", "Sistema operacional", "Linguagem de programação", "Protocolo de rede"]', 'Internet das Coisas', 'IoT conecta dispositivos físicos à internet, permitindo coleta e troca de dados.', 'easy', 'technology', '["iot", "conectividade"]'),
('O que é Cloud Computing?', '["Previsão do tempo", "Computação em nuvem", "Armazenamento local", "Software desktop"]', 'Computação em nuvem', 'Cloud Computing fornece recursos computacionais através da internet, como servidores, armazenamento e aplicações.', 'easy', 'technology', '["cloud", "computacao"]'),
('O que é API?', '["Interface de Programação", "Algoritmo avançado", "Protocolo de segurança", "Banco de dados"]', 'Interface de Programação', 'API permite que diferentes softwares se comuniquem entre si através de interfaces bem definidas.', 'medium', 'technology', '["api", "programacao"]'),
('O que é Cybersecurity?', '["Jogo de computador", "Segurança cibernética", "Sistema operacional", "Rede social"]', 'Segurança cibernética', 'Cybersecurity protege sistemas, redes e programas de ataques digitais.', 'easy', 'technology', '["seguranca", "cyber"]);

-- Inserir perguntas para categoria trading (Quantum Trading Wars)
INSERT INTO public.quiz_questions (question, options, correct_answer, explanation, difficulty, category, tags) VALUES
('O que é Day Trading?', '["Negociar apenas de dia", "Comprar e vender no mesmo dia", "Trading a longo prazo", "Investir em ações"]', 'Comprar e vender no mesmo dia', 'Day Trading envolve a compra e venda de ativos financeiros dentro do mesmo dia de negociação.', 'easy', 'trading', '["day trading", "estrategias"]'),
('O que é Stop Loss?', '["Ganho máximo", "Ordem de proteção contra perdas", "Taxa de corretagem", "Dividendo"]', 'Ordem de proteção contra perdas', 'Stop Loss é uma ordem para vender um ativo quando atinge um preço predeterminado para limitar perdas.', 'medium', 'trading', '["stop loss", "gestao risco"]'),
('O que significa Bull Market?', '["Mercado em baixa", "Mercado em alta", "Mercado lateral", "Mercado volátil"]', 'Mercado em alta', 'Bull Market refere-se a um período de crescimento contínuo nos preços dos ativos.', 'easy', 'trading', '["bull market", "tendencias"]'),
('O que é Análise Técnica?', '["Análise de fundamentos", "Estudo de gráficos e preços", "Análise de balanços", "Estudo macroeconômico"]', 'Estudo de gráficos e preços', 'Análise Técnica usa histórico de preços e volume para prever movimentos futuros.', 'medium', 'trading', '["analise tecnica", "graficos"]'),
('O que é Leverage?', '["Alavancagem financeira", "Taxa de juros", "Tipo de ação", "Estratégia conservadora"]', 'Alavancagem financeira', 'Leverage permite negociar com mais capital do que se possui, amplificando ganhos e perdas.', 'hard', 'trading', '["leverage", "alavancagem"]'),
('O que é Swing Trading?', '["Trading intraday", "Posições por dias/semanas", "Trading de alta frequência", "Investimento passivo"]', 'Posições por dias/semanas', 'Swing Trading mantém posições por alguns dias ou semanas para capturar movimentos de preço.', 'medium', 'trading', '["swing trading", "estrategias"]'),
('O que é Spread?', '["Diferença entre compra e venda", "Taxa de corretagem", "Dividendo", "Valor patrimonial"]', 'Diferença entre compra e venda', 'Spread é a diferença entre o preço de compra (bid) e venda (ask) de um ativo.', 'easy', 'trading', '["spread", "mercado"]'),
('O que é Volume?', '["Preço do ativo", "Quantidade negociada", "Taxa de juros", "Volatilidade"]', 'Quantidade negociada', 'Volume representa a quantidade de ações ou contratos negociados em um período.', 'easy', 'trading', '["volume", "liquidez"]'),
('O que é Volatilidade?', '["Estabilidade de preços", "Variação dos preços", "Tendência de alta", "Dividendos"]', 'Variação dos preços', 'Volatilidade mede o grau de variação dos preços de um ativo ao longo do tempo.', 'medium', 'trading', '["volatilidade", "risco"]'),
('O que é Scalping?', '["Trading de longo prazo", "Trading de curtíssimo prazo", "Análise fundamentalista", "Investimento passivo"]', 'Trading de curtíssimo prazo', 'Scalping busca lucros pequenos em operações muito rápidas, geralmente em minutos.', 'hard', 'trading', '["scalping", "estrategias"]);

-- Inserir perguntas para categoria cryptocurrency (Crypto Genesis Tournament)
INSERT INTO public.quiz_questions (question, options, correct_answer, explanation, difficulty, category, tags) VALUES
('Quem criou o Bitcoin?', '["Vitalik Buterin", "Satoshi Nakamoto", "Charlie Lee", "Gavin Andresen"]', 'Satoshi Nakamoto', 'Satoshi Nakamoto é o pseudônimo da pessoa ou grupo que criou o Bitcoin.', 'easy', 'cryptocurrency', '["bitcoin", "historia"]'),
('O que é uma Wallet?', '["Carteira física", "Carteira digital para criptomoedas", "Conta bancária", "Aplicativo de pagamento"]', 'Carteira digital para criptomoedas', 'Wallet é um software ou hardware que armazena chaves privadas para acessar criptomoedas.', 'easy', 'cryptocurrency', '["wallet", "seguranca"]'),
('O que é Mining?', '["Comprar criptomoedas", "Validar transações na blockchain", "Vender criptomoedas", "Criar exchanges"]', 'Validar transações na blockchain', 'Mining é o processo de validar transações e adicionar novos blocos à blockchain.', 'medium', 'cryptocurrency', '["mining", "blockchain"]'),
('O que é uma Exchange?', '["Banco tradicional", "Plataforma para negociar cripto", "Carteira digital", "Protocolo blockchain"]', 'Plataforma para negociar cripto', 'Exchange é uma plataforma que permite comprar, vender e trocar criptomoedas.', 'easy', 'cryptocurrency', '["exchange", "trading"]'),
('O que é DeFi?', '["Bitcoin", "Finanças Descentralizadas", "Tipo de carteira", "Exchange centralizada"]', 'Finanças Descentralizadas', 'DeFi refere-se a aplicações financeiras construídas em blockchains descentralizadas.', 'medium', 'cryptocurrency', '["defi", "descentralizacao"]'),
('O que é um Smart Contract?', '["Contrato físico", "Contrato auto-executável na blockchain", "Acordo bancário", "Aplicativo móvel"]', 'Contrato auto-executável na blockchain', 'Smart Contracts são programas que executam automaticamente quando condições predefinidas são atendidas.', 'hard', 'cryptocurrency', '["smart contracts", "ethereum"]'),
('O que é Staking?', '["Minerar Bitcoin", "Participar na validação da rede", "Vender criptomoedas", "Criar tokens"]', 'Participar na validação da rede', 'Staking envolve travar criptomoedas para participar da validação de transações e ganhar recompensas.', 'medium', 'cryptocurrency', '["staking", "pos"]'),
('O que é um NFT?', '["Moeda digital", "Token Não-Fungível", "Protocolo blockchain", "Tipo de mineração"]', 'Token Não-Fungível', 'NFT representa a propriedade de itens digitais únicos na blockchain.', 'easy', 'cryptocurrency', '["nft", "tokens"]'),
('O que é Ethereum?', '["Fork do Bitcoin", "Plataforma para smart contracts", "Exchange", "Carteira digital"]', 'Plataforma para smart contracts', 'Ethereum é uma plataforma blockchain que permite a criação de smart contracts e aplicações descentralizadas.', 'medium', 'cryptocurrency', '["ethereum", "plataforma"]'),
('O que é HODL?', '["Tipo de trading", "Estratégia de longo prazo", "Exchange", "Protocolo"]', 'Estratégia de longo prazo', 'HODL significa Hold On for Dear Life - estratégia de manter criptomoedas por longo prazo.', 'easy', 'cryptocurrency', '["hodl", "estrategia"]);