name: iOS TestFlight Deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Bundler
        run: gem install bundler

      - name: Install Fastlane
        run: gem install fastlane

      - name: Set up Xcode project directory
        run: cd ios

      # Se você NÃO usa CocoaPods, pode remover este passo.
      # Se for usar CocoaPods no futuro, descomente e ajuste o caminho.
      # - name: Install CocoaPods dependencies
      #   run: |
      #     cd ios
      #     if [ -f Podfile ]; then
      #       pod install
      #     fi

      - name: Build and upload to TestFlight
        working-directory: ios
        env:
          APP_STORE_CONNECT_API_KEY_ID: G8X5FP6F57
          APP_STORE_CONNECT_API_ISSUER_ID: 174886be-b08c-4e53-8de2-a6ba45aaad86 
          APP_STORE_CONNECT_API_KEY_CONTENT: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgVnCCsqkp1fYkhctqqTiPzo7Dj16BN3T/k9fALMOPGEKgCgYIKoZIzj0DAQehRANCAAQ13kC8z0RBew7HdyLn7CS8yt3ukiaICF+SiCU/pxZqoPV0PpQ1UBy7EQ+Wc8rgiUak2q6807egRdm1S7ulf5Bd
        run: fastlane beta
