name: iOS TestFlight Deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Bundler
        run: gem install bundler

      - name: Install Fastlane
        run: gem install fastlane

      - name: Build and upload to TestFlight
        working-directory: ios  # ESSENCIAL: garante que rode na pasta correta
        env:
          APP_STORE_CONNECT_API_KEY_ID: 4U7CWTXHQ2
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: 2b23890c-3caf-4628-a330-573f616db812
          APP_STORE_CONNECT_API_KEY_KEY_CONTENT: |
           -----BEGIN PRIVATE KEY-----
           MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgbRQUJW/uDxs8WIhW
           5AxipnlE6px0NSydKD6fH8XdZZCgCgYIKoZIzj0DAQehRANCAASuVgZSqFmJnCPN
           Y7rO05FJ3hXHK9WSkDjwk0KzjqBy6Jrd19GVhPvOgaD5ZMrp6WJn7cpY6sqvkxkD
           iKR0X2Ft
           -----END PRIVATE KEY-----
        run: fastlane beta
